### ISSUE TITLE
potential security problem

### ISSUE THREAD

**Issue by knrdl** [mody5bundle/capps#4]
the python code uses string concatenation to build shell commands. this could lead to command injection attacks!
as a rule of thumb `shell=True` should be avoided when interfering with the `subprocess` module. pass the command tokens as string array instead.

**Comment by mody5bundle** [comment]
can you take a look at pull request #5 ?
i'll merge when you approve.

**Comment by knrdl** [comment]
you might still run into problems, if any parameters contain spaces. See:

```python
>>> from shlex import split
>>> split('command /home/firstname lastname/test')
['command', '/home/firstname', 'lastname/test']
```

my recommendation is to just use string arrays. E.g. https://github.com/mody5bundle/capps/blob/1251d28ccd584568274296c57209eb36c972fd41/capps.py#L110 would become:
```python
    version_cmd = [
        "podman", "run", "--rm", "-it", "--entrypoint", "bash",
        image["repo"] + "/" + name,
        "-c", image["versioncmd"]
    ]
```

**Comment by mody5bundle** [comment]
I've updated the pull request with string arrays.
That actually helped a lot. The versioncmd now looks better too:  https://github.com/mody5bundle/capps/blob/ff4b1859b461d6f609e651e8766250d19568f5ac/config.yml#L14 
I'd go ahead and merge if you are out of recommendations. 
Thank you loads.

**Comment by knrdl** [comment]
Looks good to me
